version: "2.1"
services:

  database:
    image: mysql:5.7
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"

  php:
    build:
      context: ./
      dockerfile: ./.docker/php/Dockerfile
      args:
        JH_APP_DIR: "${JH_APP_DIR:-web/app}"
        JH_WP_DIR: "${JH_WP_DIR:-web/wp}"
    volumes:
      - ./.env:/var/www/.env

      # Bedrock PHP entry points
      - ./${JH_PUBLIC_DIR}/index.php:/var/www/${JH_PUBLIC_DIR}/index.php
      - ./${JH_PUBLIC_DIR}/wp-config.php:/var/www/${JH_PUBLIC_DIR}/wp-config.php

      # Bedrock Config
      - ./config:/var/www/config

      # Any themes/languages/uploads
      - ./${JH_APP_DIR}/themes:/var/www/${JH_APP_DIR}/themes
      - ./${JH_APP_DIR}/languages:/var/www/${JH_APP_DIR}/languages
      - ./${JH_APP_DIR}/uploads:/var/www/${JH_APP_DIR}/uploads

  nginx:
    build:
      context: ./
      dockerfile: ./.docker/nginx/Dockerfile
      args:
        JH_SERVER_NAME: "${JH_SERVER_NAME}"
        JH_PUBLIC_DIR: "${JH_PUBLIC_DIR}"
#    image: nginx:1.12-alpine
#    volumes:
#      - ./.docker/nginx/sample.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    ports:
      - 80:80