version: "2"

services:
  php:
    build:
      context: ./
      dockerfile: ./php/php.Dockerfile
    volumes:
      - ./.env.example:/var/www/bedrock/.env
      - ./web/app/themes:/var/www/bedrock/web/app/themes
      - ./config:/var/www/bedrock/config
    depends_on:
      - database

  nginx:
    image: nginx:1.12-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    ports:
      - 8900:80

  # The Database
  database:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=wp"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"