version: "3"

services:
  php:
    build:
      context: ./php
      dockerfile: php.Dockerfile
    volumes:
      - ./public:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:1.12-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - database

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=wp"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"