version: "2.1"
services:

  database:
    image: mysql:5.7
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"

  php:
    build:
      context: ./
      dockerfile: ./.docker/php/Dockerfile
      args:
        JH_APP_DIR: "${JH_APP_DIR:-web/app}"
        JH_WP_DIR: "${JH_WP_DIR:-web/wp}"
    volumes:
      - ./.env:/var/www/.env

      # Bedrock PHP entry points
      - ./web/index.php:/var/www/web/index.php
      - ./web/wp-config.php:/var/www/web/wp-config.php

      # Bedrock Config
      - ./config:/var/www/config

      # Any themes/languages/uploads
      - ./web/app/themes:/var/www/web/app/themes
      - ./web/app/languages:/var/www/web/app/languages
      - ./web/app/uploads:/var/www/web/app/uploads

  nginx:
    build:
      context: ./
      dockerfile: ./.docker/nginx/Dockerfile
      args:
        JH_SERVER_NAME: "${JH_SERVER_NAME}"
        JH_PUBLIC_DIR: "${JH_PUBLIC_DIR}"
#    image: nginx:1.12-alpine
#    volumes:
#      - ./.docker/nginx/sample.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    ports:
      - 80:80