version: "2"

services:

# The Database
  database:
    image: mysql:5.7
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=wp
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

  php:
    build:
      context: ./
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - ./.env.example:/var/www/.env
      - ./web/app/themes:/var/www/web/app/themes
      - ./web/app/languages:/var/www/web/app/languages
      - ./web/app/uploads:/var/www/web/app/uploads
      - ./config:/var/www/config

  nginx:
    image: nginx:1.12-alpine
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    ports:
      - 80:80